server.port=8094
spring.application.name=we-diary-bill
spring.profiles.active=dev
server.servlet.context-path=/we-diary-bill
logging.config=classpath:logback-spring.xml
management.endpoints.web.exposure.include=metrics,httptrace
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
spring.aop.proxy-target-class=true
spring.freemarker.suffix=.ftl
spring.freemarker.content-type=text/html
spring.freemarker.charset=UTF-8
spring.freemarker.cache=false
spring.freemarker.prefer-file-system-access=false
spring.freemarker.template-loader-path[0]=classpath:/templates
spring.mvc.static-path-pattern=/**
spring.resource.static-locations=classpath:/static/,classpath:/public/,file:${uploadFile.location}
uploadImages.location=/static/images
uploadFile.location=/static/images
uploadFile.resourceHandler=/static/images/**
spring.cache.type=ehcache
spring.cache.ehcache.config=classpath:ehcache.xml


mybatis-plus.mapper-locations=classpath*:cn/qingweico/modules/**/xml/*Mapper.xml,classpath*:cn/qingweico/common/**/xml/*Dao.xml
mybatis-plus.type-aliases-package=cn.qingweico.*.*.entity
mybatis-plus.global-config.banner=false
mybatis-plus.global-config.db-config.id-type=ID_WORKER_STR
mybatis-plus.global-config.db-config.table-underline=true
mybatis-plus.configuration.map-underscore-to-camel-case=true

jasypt.encryptor.password=4e61353b4f8f15af386086756312a8ee
jasypt.encryptor.ivGeneratorClassname=org.jasypt.salt.RandomIVGenerator
file.type=aliyun-oss
file.aliyun-oss.endpoint=
file.aliyun-oss.access_key_id=
file.aliyun-oss.access_key_secret=
file.aliyun-oss.bucket_name=
file.aliyun-oss.bucket_name_vehicle=
file.aliyun-oss.bucket_name_qrcoe=




oss.endpoint=
oss.access.key.id=
oss.access.key.secret=
oss.bucket.name=
