spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/blue_hour?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false\
  &serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=990712
spring.datasource.minimum-idle=5
spring.datasource.idle-timeout=1800
spring.datasource.maximum-pool-size=100
spring.datasource.auto-commit=true
spring.datasource.max-lifetime=1800000
spring.datasource.connection-timeout=30000
spring.datasource.connection-test-query=SELECT 1

