spring:
  profiles:
    active: @profile.active@
  messages:
    basename: messages
    cache-duration: 1800
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 25MB     #最大单个文件25MB,默认1MB
      max-request-size: 25MB  #单次上传最大25MB,默认10MB

server:
  port: 5000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      table-prefix: tb_
      # 设置主键生成策略
      id-type: assign_id
  type-aliases-package: cn.qingweico.entity
http:
  cors:
    enable: true
    path-pattern: /**
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    expose-headers:
      - Content-Disposition
      - Content-Length
      - Content-Type
    max-age: 3600
    allow-credentials: true
  logger:
    head: false
    media-types:
    - application/json
    - application/xml
    - text/plain
    - application/*+json
encrypt:
  sm2:
    private-key: 2a8827a3471131059f83980ba1eca1e7f20a02af717d9523ea9c58f69ae3565b
    public-key: 042d36dfdf646d71ff4380a87c653448905f02a5d6642b29c87a3fa5d63265d56c6152da1b8aa486a1b220d4138caf83ba4b69bd7da96da16b144386ff96ab57ca
