spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 990712
    hikari:
      # 最大连接数 默认值为10
      maximum-pool-size: 30
      # 最小空闲连接数 默认值为10
      minimum-idle: 30
      connection-timeout: 30000
      max-lifetime: 1800000
      idle-timeout: 600000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      table-prefix: tb_
      # 设置主键生成策略
      id-type: assign_id
  type-aliases-package: cn.qingweico.entity
server:
  port: 5000
redisson:
  mode: single  # single, cluster, sentinel, master-slave
  host: 127.0.0.1
  port: 6379
  password:
  database: 0
  timeout: 3000
  pool-size: 64
  min-idle-size: 24
http:
  cors:
    enable: true
    path-pattern: /**
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    expose-headers:
      - Content-Disposition
      - Content-Length
      - Content-Type
    max-age: 3600
    allow-credentials: true
