spring:
  profiles:
    active: @profile.active@
server:
  port: 5000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      table-prefix: tb_
      # 设置主键生成策略
      id-type: assign_id
  type-aliases-package: cn.qingweico.entity
http:
  cors:
    enable: true
    path-pattern: /**
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    expose-headers:
      - Content-Disposition
      - Content-Length
      - Content-Type
    max-age: 3600
    allow-credentials: true
