server:
  port: 8080
spring:
  data:
    mongodb:
      # use admin
      # db.createUser({
      #    user: "rw",
      #    pwd: "rw",
      #    roles: [
      #        { role: "readWrite", db: "rw_test" }
      #    ]
      #})
      uri: mongodb://rw:rw@127.0.0.1:27017/?authSource=root&authMechanism=SCRAM-SHA-1
      database: rw_test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
